# NumPY
### NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays


## Array
### Array is a data structure that stores values of same data type

In [3]:
import numpy as np

In [5]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [8]:
len(arr)

5

In [9]:
arr[0]

1

In [13]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,0]
my_lst3 = [0,3,6,9,0]

arr= np.array([my_lst1,my_lst2,my_lst3])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [0 3 6 9 0]]


In [14]:
arr.shape

(3, 5)

In [25]:
arr.reshape(5,3)  # 5*3, 3*5, 15*1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 3],
       [6, 9, 0]])

## Indexing

In [26]:
arr= np.array([1,2,3,3,4,5])
arr

array([1, 2, 3, 3, 4, 5])

In [27]:
arr[2]

3

In [32]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0],[0,3,6,9,0]])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [0, 3, 6, 9, 0]])

In [34]:
arr[1:,3:]     #from row one to end of row and from colunm three to end of colunm. [1:2,3:4]

array([[9, 0],
       [9, 0]])

In [35]:
arr[1:,2:4]  #colunm 2 and 3

array([[8, 9],
       [6, 9]])

In [36]:
arr[1,2]

8

In [37]:
arr[0:2,1]

array([2, 7])

In [38]:
arr[1,1:4]

array([7, 8, 9])

In [39]:
arr[1:,4]

array([0, 0])

In [45]:
arr = np.arange(0,10,step=3)

In [46]:
arr

array([0, 3, 6, 9])

In [54]:
arr = np.linspace(1,10,15)

In [55]:
arr

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [56]:
#copy function

In [57]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[3:] =100  # at 3 index all the next element will be 100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [59]:
arr1 = arr
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [60]:
arr1[3:] = 500
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [61]:
# so it changes the value of arr also.

In [62]:
arr1 = arr.copy() #it just copy the element at another memory location, it doesn't sharing the memory location 

In [63]:
arr1[3:] = 1000
arr1

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [64]:
arr  #It still remain same

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [66]:
# some condition very useful in exploratary data analysis
arr= np.arange(1,10)

val = 2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [68]:
arr[arr<2]

array([1])

In [69]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
arr%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [72]:
arr= np.arange(0,10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
arr= np.arange(0,15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [76]:
arr= np.arange(0,20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
#inbuilt function -- shape,reshape,arange,copy,linspace,ones

In [79]:
np.ones(4)

array([1., 1., 1., 1.])

In [80]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [82]:
np.ones((4,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
# random.randn

In [88]:
arr_rn = np.random.randn(4,4)

arr_rn   #value will change each and very time we run the program

array([[-0.74967818, -0.23578174,  0.58378432,  2.89435239],
       [-1.2685506 ,  0.26482154,  1.41580849,  0.34964744],
       [-2.4338098 , -0.42445598, -0.11336543, -1.23254861],
       [ 1.13035701, -0.70956233, -0.59399916, -1.51755654]])

In [89]:
np.random.randn(3,5)

array([[ 1.43009578,  0.02753978, -0.05790295, -1.24822757,  0.64960161],
       [-0.67348463,  1.00345834, -0.51456468, -0.83988657, -0.74951634],
       [ 0.12253173, -0.26597062,  0.03573097,  1.67863609,  0.36232646]])

In [102]:
# randon.randint(start,end,no. of element)

In [92]:
np.random.randint(1,100,8) 

array([63, 17, 41, 65, 28, 70, 13,  2])

In [103]:
arr =np.random.randint(1,100,15) 
arr

array([70, 44, 40, 49, 49, 26, 34, 26, 38, 58, 10, 23, 61,  7, 56])

In [105]:
np.random.random_sample((1,5))

array([[0.77295227, 0.83123915, 0.40037804, 0.84970653, 0.31010319]])